### ISSUE TITLE
Error Starting Project

### ISSUE THREAD

**Issue by imThaku** [konfer-be/ts-express-typeorm-boilerplate#2]
Hello i have some trouble on starting project.
i used
`nodemon  ./src/api/app.bootstrap.ts`

but i have this error:
` Cannot find module '@servers/mysql.server'`

can you help me to start the project ?

**Comment by konfer-be** [comment]
You don't have to start the Typescript files but the files generated in native javascript. Make sure that the js files have been generated, otherwise simply run the tsc command at the root of the project. Then start the project by attacking the ./dist/app/ directory.
