### ISSUE TITLE
Sanitizer is not working for response

### ISSUE THREAD

**Issue by mizan-dharma** [konfer-be/ts-express-typeorm-boilerplate#7]
Hi 

whenever i call the login API, i get the full data. the whitelist filter is not working for sanitizing the data. Can you please let me know if there is anything missing in the setup or its a legit issue. 

{
    "token": {
        "tokenType": "Bearer",
        "accessToken": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2MjI4MTYxOTMsImlhdCI6MTYxNTU1ODU5Mywic3ViIjoxfQ.8FQyaJyuj_CbAOOpiMKpEYLTkwOC8mEYW94w3l17wqE",
        "refreshToken": "1.0ed40da504b505a5d1ceca31bdd0765e77fc905d7721345a6d060bb9827de7d72eb83a14d51809ca",
        "expiresIn": "2021-06-04T14:16:33.809Z"
    },
    "user": {
        "id": 1,
        "username": "john-doe",
        "email": "contact@john-doe.com",
        "password": "$2b$10$bW42twvRzce3WtiR926D0OIBgjoiHE0sb32dScN1JV36GEtcQLj2S",
        "apikey": "contact@johndoe.combA2xcjpf8y5aSUFsNB2qN5yymUBSs6es3qHoFpGkec75R",
        "role": "user",
        "createdAt": "2021-03-12T16:17:01.410Z",
        "updatedAt": null,
        "deletedAt": null,
        "medias": [],
        "temporaryPassword": "$2b$10$bW42twvRzce3WtiR926D0OIBgjoiHE0sb32dScN1JV36GEtcQLj2S"
    }
}

best regards, 
Mizan

**Comment by konfer-be** [comment]
Hi Mizan,

Yes this is a known bug: the sanitizer don't manage the case when the data to returns is a litteral object which aggregate mixed data. This is fixed but not already deployed. You can fix that in the sanitizer.middleware or stay tunned for the next version ;-)

**Comment by mizan-dharma** [comment]
Thanks. Will wait for the next release. I made a quick fix for now and its working fine. 

Btw, do you have a roadmap for the upcoming versions. that will be great to have. 

Keep up the good work.

**Comment by konfer-be** [comment]
Hi Mizan. Bug was fixed in the v1.2.0, with a lot of other improvements. You can pull this last version. The roadmap is in progress and should comes with a further minor release. Contributors are welcome in the next few months ;-)
